name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: |
        cd off-chain
        npm cache clean --force
        npm ci
      
    - name: Run tests
      run: |
        cd off-chain
        npm test
      
    - name: Build
      run: |
        cd off-chain
        npm run build